# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf18d05de71a3f82463e4f363d7996eb671e2f37622e96c7c7e34f17871f510d25393b762928142b0b30b1558dd8bf8801bf8486a185c5c6ab301183230ebe8

test:
  secret_key_base: 7d97611fa373d4885e31138a22a5a820d9e97a79126b7f691686dc2d7aa1ad68045c26b5b6efb2cdc4c762fbf923c62ea7873d7908d3773f90d938f85277308c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
